services:
  accidents_db:
    build:
      context: .
      dockerfile: Dockerfile.accidents_db
    container_name: db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accidents_db
    ports:
      - "5432:5432"
    volumes:
      - accidents_db_data:/var/lib/postgresql/data
volumes:
  accidents_db_data: