FROM minio/minio:RELEASE.2025-09-07T16-13-09Z

# Copy the custom entrypoint script and make it executable
COPY scripts/minio-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["server", "/data", "--console-address", ":9001"]